import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({ quote }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Notion App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {JSON.stringify(quote)}
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch('https://api.breakingbadquotes.xyz/v1/quotes')
  const data = await res.json()

  const quote = data[0].quote

  return {
    props: {
      quote,
    },
  }
}